"""create claim model

Revision ID: ae2f877d8240
Revises: 
Create Date: 2025-02-18 12:00:42.410925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae2f877d8240'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Claim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submitted_procedure', sa.String(length=7), nullable=False),
    sa.Column('quadrant', sa.String(length=10), nullable=True),
    sa.Column('plan_group', sa.String(), nullable=True),
    sa.Column('subscriber', sa.BigInteger(), nullable=True),
    sa.Column('provider_npi', sa.BigInteger(), nullable=True),
    sa.Column('provider_fees', sa.Float(), nullable=True),
    sa.Column('allowed_fees', sa.Float(), nullable=True),
    sa.Column('member_coinsurance', sa.Float(), nullable=True),
    sa.Column('member_copay', sa.Float(), nullable=True),
    sa.Column('net_fee', sa.Float(), nullable=True),
    sa.Column('service_date', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updatedAt', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Claim_id'), 'Claim', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Claim_id'), table_name='Claim')
    op.drop_table('Claim')
    # ### end Alembic commands ###
